---
apiVersion: v1
kind: ConfigMap

metadata:
  name: koochooloo-config
  labels:
    app: koochooloo
data:
  config.yml: |-
    debug: false
    database:
      dialect: postgres
      url: "host=koochooloo-postgres user=koochooloo password=secret dbname=koochooloo port=5432 sslmode=disable"
