---
name: "koochooloo"
services:
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: koochooloo
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: koochooloo
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U koochooloo -d koochooloo"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - target: 4317
        published: 4317
        protocol: tcp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp
