---
name: "koochooloo"
services:
  database:
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - target: 4317
        published: 4317
        protocol: tcp
      - target: 16686
        published: 16686
        protocol: tcp
      - target: 14268
        published: 14268
        protocol: tcp
