---
kind: pipeline
name: default
type: docker

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --enable-all
  - name: migrate
    image: golang
    environment:
      koochooloo_database_url: "mongodb://database:27017"
      koochooloo_database_name: "koochooloo"
    command:
      - go run main.go migrate
  - name: test
    image: golang
    environment:
      koochooloo_database_url: "mongodb://database:27017"
      koochooloo_database_name: "koochooloo"
    commands:
      - go test -v ./...
  - name: docker
    image: plugins/docker
    settings:
      username: 1995parham
      password:
        from_secret: docker_password
      repo: 1995parham/koochooloo
      tags: latest

services:
  - name: database
    image: mongo:latest