---
version: "2"
linters:
  default: all
  disable:
    - depguard
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    - revive
    - wrapcheck
    - noinlineerr
    # temporary until fix happen in otel exporters
    - gomoddirectives

  settings:
    wrapcheck:
      ignore-sigs:
        - .JSON
        - .NewHTTPError
        - .Redirect
        - .NoContent
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
