---
linters:
  enable-all: true
  disable:
    # we don't use json with camel-case
    - tagliatelle
    - nolintlint
    # it should improve to support more known patterns
    - varnamelen
    - ireturn
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
    - exhaustivestruct
linters-settings:
  wrapcheck:
    ignoreSigs:
      - .JSON
      - .NewHTTPError
      - .Redirect
      - .NoContent
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
