---
logger:
  level: "info"
database:
  url: mongodb://127.0.0.1:27017
  name: koochooloo
monitoring:
  address: ":8080"
  enabled: true
telemetry:
  trace:
    enabled: true
    url: http://127.0.0.1:14268
