---
name: test
on:
  - push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v3
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - run: just test
      - uses: codecov/codecov-action@v5.5.1
        with:
          files: coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 1995parham/koochoolooo

  docker:
    name: docker
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/bake-action@v6
        with:
          files: "build/package/docker-bake.json"
          push: true
